import ArticleLayout from '../../components/ArticleLayout'

function ShortFormArticle() {
  return (
    <ArticleLayout
      title="The Rise of Short-Form Content"
      date="2023.04.28"
      footerLink="https://uhsdevilsadvocate.weebly.com/ai-an-existential-threat.html"
      footerText="Taken from the Devil's Advocate May 2023 Issue"
    >
      <p className="body-paragraph">
        Perhaps you are stuck on a long car ride, taking the bus, or just sprawled out on your bed, but your mind drifts away from school and life and towards your phone. You go on Instagram, and at the bottom of the screen, you navigate to your Reels. You go on Snapchat, and there are so many Stories. Youtube now has Youtube Shorts, which is just a boldfaced copy of the original, Tiktok. The rise of short-form content started gradually, but in the past few years has exploded in popularity across all of the major social media platforms. Going back to the now-defunct Vine, which pioneered the medium with six second videos, it now seems like every major platform has some sort of scrollable feed of content for us to waste our time with.
      </p>
      <p className="body-paragraph">
        There are many positive things about short-form content, and it would not be viable in our hyper-competitive world if it didn't have broad appeal to people that are online. The first is that media can be extremely tailored to each user, bettering their experience on the platform. Many sites have experimented with different ways to deliver it to users, but none has done better than Tiktok. Almost universally praised for having one of the best recommendation algorithms on any social media platform, Tiktok has an almost eerie way of keeping you addicted, continuously scrolling through videos. Each person can find a subgenre or niche of the internet where there are people exactly like them, and the content is suited perfectly for them. And because of the short nature, there will never be an end to this flow. Short-form content is arguably easier to produce than long-form, which means that almost everyone can do it, and there are constantly new ideas cropping up, with no one video lasting for very long. With essentially no barrier to start creating, these platforms have greatly accelerated the idea of "Broadcast Yourself", or Youtube's original 2005 slogan. Snapchat and Tiktok now host a slew of filters and video editing tools that are accessible to the layman, making everyone their creator. All you need is a phone and some time on your hands. Similar to meme culture on the internet, the rapid stream of ideas and trends is ever-changing and mutating, pushing viral ideas to the top and burying others. This creates an environment that promotes creating massive amounts of content, in hopes that your video will be the next big thing. Sites like Tiktok and Youtube Shorts are at the forefront of innovation in today's culture, with some being more creative and culturally relevant than others.
      </p>
      <p className="body-paragraph">
        Still, there are many downsides to this new age of media, and I've personally felt like they are increasingly affecting me in negative ways. You may have heard of the term instant gratification, which comes from scientific research done on the opposite phenomenon of delayed gratification. Delayed gratification is when a subject resists the temptation of a smaller, more immediate reward in favor of a larger reward later, such as waiting for multiple episodes of a TV show to release so that you can binge them all at once. This usually requires skills such as patience, self-control, and willpower, and is generally associated with positive outcomes like academic success and physical & mental health. The issue comes when gratification is not withheld, and given freely and constantly. We live in a day and age where if we want food, entertainment, clothing, or other consumables, they are incredibly easy to obtain quickly, and with no real resistance. Companies market their lack of resistance as a feature, rather than the problem that it is. Human brains change all the time in response to stimuli, but when we continually get high levels of dopamine from places like TikTok, it can train our brains to respond to the wrong stimuli. This is how people develop addictions to the fat and sugar in certain fast foods or become shopaholics. It's not always a conscious choice, with our brain chemistry controlling more of our actions than we think. Tiktok recently released a paper on their algorithm, and they have specifically engineered it to respond quickly to what a user likes and dislikes, all to keep them hooked for as long as possible. With a constant stream of things that we like, the high dopamine levels can keep us attached for hours at a time.
      </p>
      <p className="body-paragraph">
        I'm not on any social media such as Tiktok, Instagram, or Snapchat, but I still feel the effects of instant gratification in my daily life. I'm on my phone more than ever before, even when there's nothing for me to do. I'll instinctually grab it and open the same quick succession of apps, hoping to see something new pop up. I have to remind myself that glancing at the titles of articles is not nearly enough to stay informed, and my attention span is shorter than ever. This is not just anecdotal, and data has shown that the attention span of the public is collapsing, being less than that of a goldfish. Gen Z has grown up as this technology was being created, and the cycles of dopamine affect developing brains even more. So next time your parents tell you to get off your phone, you can blame society.
      </p>
      <p className="body-paragraph">
        It's not all bad though, and there are steps you can take to remedy a failing attention span. The first is to think about your actions and do things with intention. Instead of mindlessly opening up your phone every time you feel boredom creeping over you, make a conscious decision about what you want to do. Maybe that is putting your phone away, and engaging in a conversation with someone or taking in your surroundings. Maybe it does mean staying on your phone, but to be intentional with what apps you are using, instead of just mindlessly scrolling. I've been working hard to get my attention span back to where it used to be before the horde of shorts content and instant gratification took over internet media. Even though the internet is working to go faster and faster each day, I'm just trying to slow down for once.
      </p>
    </ArticleLayout>
  )
}

export default ShortFormArticle
